In [3]:
# numpy is a numerical python
#import numpy as np
import numpy as np

In [4]:
b=np.array([[1,2,3],[4,5.5,6],[-7,8,9]])

In [5]:
type(b)

numpy.ndarray

In [6]:
b.shape

(3, 3)

In [7]:
b[1,2]

6.0

In [8]:
b[0,1]

2.0

In [9]:
b[1]

array([4. , 5.5, 6. ])

In [10]:
b[1,:]

array([4. , 5.5, 6. ])

In [11]:
b[:,1]

array([2. , 5.5, 8. ])

In [12]:
b[1:]

array([[ 4. ,  5.5,  6. ],
       [-7. ,  8. ,  9. ]])

In [26]:
c=np.array([[10,25,30,40],[12,27,32,42],[14,29,34,44]])

In [27]:
type(c)

numpy.ndarray

In [28]:
c[1,2]

32

In [29]:
c[[0,2,1],[1,2,0]]

array([25, 34, 12])

In [37]:
c[[2,0,1,2],[3,0,2,0]]=[0,0,0,0]

In [38]:
c

array([[ 0, 25, 30, 40],
       [12, 27,  0, 42],
       [ 0, 29, 34,  0]])

In [40]:
import math

In [53]:
c[2]=np.sqrt(c[2])

In [54]:
c

array([[ 0, 25, 30, 40],
       [ 3,  5,  0,  6],
       [ 0,  5,  5,  0]])

In [55]:
c

array([[ 0, 25, 30, 40],
       [ 3,  5,  0,  6],
       [ 0,  5,  5,  0]])

In [56]:
b=np.array([[1,2,3],[4,5.5,6],[-7,8,9]])

In [57]:
np.sum(b)

31.5

In [58]:
np.sum(b,axis=0)

array([-2. , 15.5, 18. ])

In [59]:
b

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5.5,  6. ],
       [-7. ,  8. ,  9. ]])

In [62]:
np.sum(b,axis=1)=b

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (488753968.py, line 1)

In [63]:
b

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5.5,  6. ],
       [-7. ,  8. ,  9. ]])

In [65]:
b=np.array([[-10,40,20],[20,-20,40],[40,20,-40]])

In [66]:
b

array([[-10,  40,  20],
       [ 20, -20,  40],
       [ 40,  20, -40]])

In [71]:
b=np.array([[1]])

In [6]:

np.arange(2,10)

NameError: name 'np' is not defined

In [7]:
np.arange(start=2, stop=10, num=25)

NameError: name 'np' is not defined

In [8]:
import numpy as np

In [9]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(start=2,stop=10,num=25)

array([ 2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ,
        5.33333333,  5.66666667,  6.        ,  6.33333333,  6.66666667,
        7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
        8.66666667,  9.        ,  9.33333333,  9.66666667, 10.        ])

In [11]:
np.random.randint(high=10,low=1,size=(3,3))

array([[7, 8, 2],
       [6, 2, 4],
       [2, 1, 2]])

In [12]:
np.random.random( size=(3,4))

array([[0.69895197, 0.99863264, 0.95402121, 0.12598171],
       [0.63137391, 0.01096742, 0.29217331, 0.95788944],
       [0.33507471, 0.39413171, 0.7319112 , 0.21265654]])

In [3]:
np.random.randint(high=1000,low=5,size=(2000))
import numpy as np

NameError: name 'np' is not defined

In [4]:
np.random.randint(high=30,low=20,size=(20)

SyntaxError: incomplete input (1668203125.py, line 1)

In [5]:
import numpy as np

In [9]:
y=np.random.randint(high=30,low=20,size=(20))

In [10]:
np.random.choice(y,6)

array([20, 24, 23, 29, 23, 29])

In [12]:
np.random.choice(y,6,replace=False)

array([23, 25, 23, 24, 24, 20])

In [13]:
np.random.choice(["a","b"],6)

array(['b', 'a', 'b', 'a', 'a', 'a'], dtype='<U1')

In [14]:
np.random.choice(["a","b"],1000)

array(['a', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'b', 'b', 'a', 'a', 'a',
       'a', 'b', 'b', 'a', 'b', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b',
       'b', 'a', 'b', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
       'b', 'b', 'a', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'b', 'a',
       'b', 'b', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'b', 'b', 'b',
       'b', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'a', 'a', 'b',
       'a', 'a', 'a', 'b', 'a', 'b', 'b', 'a', 'b', 'a', 'a', 'a', 'b',
       'a', 'b', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'a', 'b', 'b',
       'b', 'b', 'b', 'b', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'b',
       'b', 'a', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'b',
       'a', 'b', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'a',
       'a', 'b', 'a', 'a', 'a', 'a', 'b', 'a', 'b', 'b', 'b', 'a', 'a',
       'a', 'b', 'b', 'a', 'b', 'b', 'b', 'a', 'b', 'b', 'b', 'a', 'a',
       'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'b

In [15]:
y=np.random.choice(["a","b"],1000)

In [1]:
np.unique(y,return_counts=True)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
y=np.random.choice(["a","b"],1000,p=[0.8,0.2])

In [4]:
y

array(['a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b',
       'a', 'a', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'a', 'a', 'a', 'b',
       'a', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a',
       'a', 'b', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'b', 'a', 'a', 'a',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
       'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'a',
       'b', 'a', 'a', 'a', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a',
       'a', 'a', 'b', 'b', 'a', 'b', 'b', 'b', 'a', 'a', 'a', 'a', 'b',
       'a', 'a', 'a', 'a', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a',
       'a', 'b', 'a', 'a', 'b', 'b', 'a', 'a', 'b', 'a', 'a', 'a', 'a',
       'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'a', 'a', 'a',
       'a', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b',
       'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a

In [5]:
np.unique(y,return_counts=True)

(array(['a', 'b'], dtype='<U1'), array([801, 199], dtype=int64))

In [6]:
z=np.random.randint(high=100,low=1,size=(40))

In [7]:
z

array([59, 92, 93, 85, 71, 38,  1, 92, 48, 77, 51, 90, 29,  2, 30, 79, 98,
       54, 94, 86, 58, 52, 40, 91, 41, 77, 78, 51, 11, 96, 68, 65, 26,  6,
       78, 89, 70, 37, 32, 22])

In [9]:
z.max()

98

In [10]:
z.min()

1

In [11]:
z.argmax()

16

In [12]:
z=np.random.randint(high=100,low=12,size=(24))

In [13]:
z

array([41, 85, 30, 96, 22, 42, 26, 21, 31, 62, 15, 29, 69, 31, 52, 21, 55,
       96, 70, 97, 42, 71, 95, 14])

In [14]:
x=np.random.randint(high=100,low=12,size=(4,6))

In [15]:
x

array([[48, 24, 33, 15, 20, 15],
       [92, 82, 89, 65, 66, 69],
       [41, 73, 64, 69, 49, 91],
       [71, 23, 82, 59, 68, 44]])

In [16]:
x[:,2]

array([33, 89, 64, 82])

In [17]:
x[:,2].argsort()

array([0, 2, 3, 1], dtype=int64)

In [18]:
x[x[:,2].argsort(),:]

array([[48, 24, 33, 15, 20, 15],
       [41, 73, 64, 69, 49, 91],
       [71, 23, 82, 59, 68, 44],
       [92, 82, 89, 65, 66, 69]])

In [15]:
import numpy as np

In [16]:
id=np.arange(1,51)

In [17]:
rating=np.random.choice(["good","bad","excellent","pathetic"],50)

In [18]:
city=np.random.choice(["bangalore","mumbai","chennai"],50)

In [19]:
children=np.random.randint(high=5,low=0,size=(50))

In [20]:
fico=np.random.choice(["100-150","150-200","200-250"],50)

In [21]:
balance=np.random.choice([1000,2000,3000,np.nan,4000],50)

In [23]:
age=np.random.randint(high=70,low=15,size=(50))

In [24]:
balance

array([3000., 3000.,   nan,   nan, 1000., 1000., 2000., 3000., 3000.,
         nan, 1000.,   nan,   nan, 2000., 3000., 3000., 2000.,   nan,
       1000.,   nan, 4000., 1000.,   nan, 4000., 2000., 1000., 1000.,
       1000., 2000.,   nan, 3000., 4000., 4000.,   nan, 3000., 3000.,
         nan, 2000., 3000., 1000.,   nan, 3000., 2000.,   nan,   nan,
       3000., 3000., 3000., 4000., 3000.])

In [25]:
balance

array([3000., 3000.,   nan,   nan, 1000., 1000., 2000., 3000., 3000.,
         nan, 1000.,   nan,   nan, 2000., 3000., 3000., 2000.,   nan,
       1000.,   nan, 4000., 1000.,   nan, 4000., 2000., 1000., 1000.,
       1000., 2000.,   nan, 3000., 4000., 4000.,   nan, 3000., 3000.,
         nan, 2000., 3000., 1000.,   nan, 3000., 2000.,   nan,   nan,
       3000., 3000., 3000., 4000., 3000.])

In [26]:
age

array([18, 57, 66, 64, 63, 35, 22, 22, 61, 53, 58, 38, 19, 31, 28, 38, 47,
       42, 54, 49, 49, 33, 22, 15, 58, 54, 18, 24, 69, 16, 69, 56, 65, 50,
       59, 23, 53, 35, 33, 52, 42, 23, 50, 16, 53, 66, 18, 22, 34, 27])

In [27]:
fico

array(['100-150', '150-200', '100-150', '150-200', '200-250', '150-200',
       '150-200', '100-150', '150-200', '100-150', '200-250', '100-150',
       '200-250', '100-150', '150-200', '100-150', '200-250', '100-150',
       '100-150', '150-200', '200-250', '150-200', '200-250', '100-150',
       '150-200', '150-200', '200-250', '150-200', '150-200', '150-200',
       '100-150', '100-150', '100-150', '100-150', '200-250', '200-250',
       '200-250', '150-200', '150-200', '150-200', '200-250', '100-150',
       '150-200', '100-150', '200-250', '150-200', '100-150', '100-150',
       '100-150', '150-200'], dtype='<U7')

In [28]:
children

array([3, 3, 3, 4, 1, 2, 3, 3, 3, 4, 2, 0, 2, 2, 1, 1, 4, 3, 2, 0, 4, 2,
       2, 0, 4, 2, 4, 0, 3, 0, 4, 1, 0, 0, 1, 2, 1, 3, 3, 2, 2, 4, 3, 0,
       0, 3, 2, 0, 4, 2])

In [29]:
rating

array(['pathetic', 'good', 'pathetic', 'bad', 'bad', 'pathetic', 'bad',
       'excellent', 'good', 'excellent', 'excellent', 'bad', 'good',
       'excellent', 'bad', 'good', 'excellent', 'good', 'bad', 'good',
       'good', 'good', 'pathetic', 'bad', 'bad', 'pathetic', 'pathetic',
       'pathetic', 'pathetic', 'pathetic', 'bad', 'good', 'good',
       'excellent', 'pathetic', 'bad', 'pathetic', 'excellent',
       'excellent', 'good', 'good', 'good', 'bad', 'pathetic', 'pathetic',
       'bad', 'pathetic', 'bad', 'pathetic', 'excellent'], dtype='<U9')

In [30]:
id

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [31]:
import pandas as pd

In [32]:
df=pd.DataFrame({"ID":id,"RATING":rating,"CITY":city,"FICO":fico,"BALANCE":balance,"AGE":age})

In [33]:
df

ID     RATING       CITY     FICO  BALANCE  AGE
0    1   pathetic     mumbai  100-150   3000.0   18
1    2       good     mumbai  150-200   3000.0   57
2    3   pathetic     mumbai  100-150      NaN   66
3    4        bad    chennai  150-200      NaN   64
4    5        bad     mumbai  200-250   1000.0   63
5    6   pathetic    chennai  150-200   1000.0   35
6    7        bad    chennai  150-200   2000.0   22
7    8  excellent     mumbai  100-150   3000.0   22
8    9       good  bangalore  150-200   3000.0   61
9   10  excellent     mumbai  100-150      NaN   53
10  11  excellent     mumbai  200-250   1000.0   58
11  12        bad  bangalore  100-150      NaN   38
12  13       good    chennai  200-250      NaN   19
13  14  excellent     mumbai  100-150   2000.0   31
14  15        bad    chennai  150-200   3000.0   28
15  16       good  bangalore  100-150   3000.0   38
16  17  excellent  bangalore  200-250   2000.0   47
17  18       good  bangalore  100-150      NaN   42
18  19        bad    chennai  100-150   1000.0   54
19  20       good     mumbai  150-200      NaN   49
20  21       good    chennai  200-250   4000.0   49
21  22       good  bangalore  150-200   1000.0   33
22  23   pathetic  bangalore  200-250      NaN   22
23  24        bad  bangalore  100-150   4000.0   15
24  25        bad  bangalore  150-200   2000.0   58
25  26   pathetic     mumbai  150-200   1000.0   54
26  27   pathetic  bangalore  200-250   1000.0   18
27  28   pathetic    chennai  150-200   1000.0   24
28  29   pathetic  bangalore  150-200   2000.0   69
29  30   pathetic     mumbai  150-200      NaN   16
30  31        bad     mumbai  100-150   3000.0   69
31  32       good  bangalore  100-150   4000.0   56
32  33       good    chennai  100-150   4000.0   65
33  34  excellent  bangalore  100-150      NaN   50
34  35   pathetic  bangalore  200-250   3000.0   59
35  36        bad  bangalore  200-250   3000.0   23
36  37   pathetic    chennai  200-250      NaN   53
37  38  excellent     mumbai  150-200   2000.0   35
38  39  excellent  bangalore  150-200   3000.0   33
39  40       good     mumbai  150-200   1000.0   52
40  41       good     mumbai  200-250      NaN   42
41  42       good     mumbai  100-150   3000.0   23
42  43        bad     mumbai  150-200   2000.0   50
43  44   pathetic  bangalore  100-150      NaN   16
44  45   pathetic     mumbai  200-250      NaN   53
45  46        bad     mumbai  150-200   3000.0   66
46  47   pathetic     mumbai  100-150   3000.0   18
47  48        bad     mumbai  100-150   3000.0   22
48  49   pathetic  bangalore  100-150   4000.0   34
49  50  excellent    chennai  150-200   3000.0   27

In [54]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df["CITY"].value_counts()

mumbai       21
bangalore    18
chennai      11
Name: CITY, dtype: int64

In [53]:
df["CITY_bangalore"]=np.where(df["CITY"]=="bangalore",1,0)

In [54]:
df["CITY_bangalore"]

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     1
9     0
10    0
11    1
12    0
13    0
14    0
15    1
16    1
17    1
18    0
19    0
20    0
21    1
22    1
23    1
24    1
25    0
26    1
27    0
28    1
29    0
30    0
31    1
32    0
33    1
34    1
35    1
36    0
37    0
38    1
39    0
40    0
41    0
42    0
43    1
44    0
45    0
46    0
47    0
48    1
49    0
Name: CITY_bangalore, dtype: int32

In [56]:
df['constant']=100

In [57]:
df['log_balance']=np.log(balance)

In [60]:
df['RATING'].value_counts()

pathetic     15
good         13
bad          13
excellent     9
Name: RATING, dtype: int64