In [1]:
import numpy as np
#Linear Algebra, Determinants & Matrices: - 
#We use this library to form data arrays using python which is a homogentic arrangement of elements across the structure.
#we require this to make data arrays and so that the data can be analyzed perfectly.

In [2]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [3]:
#Dimension of an array: - 
a.ndim

2

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.itemsize

4

In [6]:
a.shape

(3, 3)

In [7]:
#Scalar (0 D Array): - 
scalar = np.array(56)
print("Scalar",scalar)
print("ndim:",scalar.ndim)

#1D Array: - 
arr_1d = np.array([1,2,3,4])
print("\n1D Array:",arr_1d)
print("ndim:",arr_1d.ndim)

#2D Array: - 
arr_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D Array:",arr_2d)
print("ndim:",arr_2d.ndim)

#3D Array: - 
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)

Scalar 56
ndim: 0

1D Array: [1 2 3 4]
ndim: 1

2D Array: [[1 2 3]
 [4 5 6]]
ndim: 2

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [8]:
# 2 code blocks, 2 rows & 2 columns
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)


3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [9]:
# 2 groups, 2 code blocks, 3 rows & 4 columns
arr_4d = np.array([
    [ # First Group
        [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #First Block
        [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #Second Block
    ],
    [# Second Group
        [[25,26,27,28],[29,30,31,32],[33,34,35,36]],
        [[37,38,39,40],[41,42,43,44],[45,46,47,48]]
    ]
])
print("\n4D Array:",arr_4d)
print("ndim:",arr_4d.ndim)


4D Array: [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
ndim: 4


### Data Manipulations using Arrays: -

In [11]:
import numpy as np

In [12]:
#Create a 3D array - 
array_3d = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #first Block
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #second Block
])

print("3d_Array:")
print(array_3d)

#Shape of the array: - (Output Syntax: - Block, Row, Column)
print("\n shape of the array is:",array_3d.shape)

#Access elements: - (Output Syntax: - Indices # of [Block, Row, Column])
print("\nElement at block 1, row 2, column 3:",array_3d[0,1,2])
print("\nElement at block 2, row 3, column 2:",array_3d[1,2,1])

#Access all the elements: - 
print("\n Second Block: ")
print(array_3d[1])

#Access the specific set of elements: - 
print("\n first column of each block")
print(array_3d[:,:,0])

print("\n first row of each block")
print(array_3d[:,0,:])

print("\n specific set of elements") #Indices of [Block, Row, Column]
result = (array_3d[0,0:2,0:2])
result_1 = (array_3d[1,1:3,2:4])

print("\n specific set of sliced elements")
result_2 = (array_3d[:,1,1:3]) 

print("\n Extracted Elements:")
print(result.flatten())

print("\n Extracted Elements:")
print(result_1.flatten())

print("\n Extracted Elements:")
print(result_2.flatten())

3d_Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

 shape of the array is: (2, 3, 4)

Element at block 1, row 2, column 3: 7

Element at block 2, row 3, column 2: 22

 Second Block: 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

 first column of each block
[[ 1  5  9]
 [13 17 21]]

 first row of each block
[[ 1  2  3  4]
 [13 14 15 16]]

 specific set of elements

 specific set of sliced elements

 Extracted Elements:
[1 2 5 6]

 Extracted Elements:
[19 20 23 24]

 Extracted Elements:
[ 6  7 18 19]


## Array Methods: - 

### 1. Array creation Methods

In [15]:
# np.array() - Converts a list or a tuple into an array.
arr_345 = np.array([1,2,3,4])
arr_345

array([1, 2, 3, 4])

In [77]:
#Practical Application: - 
'''We are considering a weather monitoring system where we collect 
temperature data for varios cities over several days'''

temps_manual = np.array([[30,32,33,35,31,29,30], # Temperature of City_1
                         [28,27,29,31,30,26,27]]) #Temperature of City_2

In [17]:
#np.zeroes() - Creates an array filled with zeroes.
arr_678 = np.zeros((2,3))
arr_678

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
#Practical Application: -
temps_empty = np.zeros((5,7))
print(temps_empty)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:
#np.ones() - Creates an array filled with ones.
arr_897 = np.ones((2,3))
arr_897

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
#Practical Application: -
temps_ones = np.ones((5,7))

In [81]:
#np.arange() - creates an array with a range of numbers.
art_978 = np.arange(1,11,3)

In [20]:
art_978

array([ 1,  4,  7, 10])

In [85]:
#Practical Application: -

timestamps = np.arange(0,24,1)
timestamps

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
#np.linspace(): - Creates an array with evenly spaced numbers
art_765 = np.linspace(0,2,5)

In [87]:
#Practical Application: -

'''Record evenly spaced temperatures between highest and lowest values.'''

lin_temp = np.linspace(26,35,5)
lin_temp

array([26.  , 28.25, 30.5 , 32.75, 35.  ])

In [22]:
art_765

array([0. , 0.5, 1. , 1.5, 2. ])

#### To make any data a dataframe: - 

In [23]:
#Pandas Solution: - 
data = {
    "Name": ["Prabha","James","Susan"],
    "Maths": [67,89,92],
    "Physics": [48,57,91]
}

In [24]:
data

{'Name': ['Prabha', 'James', 'Susan'],
 'Maths': [67, 89, 92],
 'Physics': [48, 57, 91]}

In [25]:
import pandas as pd
df_1 = pd.DataFrame(data)

In [26]:
df_1

Name  Maths  Physics
0  Prabha     67       48
1   James     89       57
2   Susan     92       91

In [67]:
#numpy solution: - 
data_2 = np.array(
    [
    ("Prabha", 67,48,57,87,58),
    ("James", 89,57,78,88,100),
    ("Susan", 92,91,31,91,99)
],
dtype = [("Name","U10"),("Maths","i4"),("Physics","i4"),("Chemistry","i4"),("Accounting","i4"), ("B.S", "i4")]                 
)
dft = pd.DataFrame(data_2)
print("\n structured data shall be: ")
print(dft)


 structured data shall be: 
     Name  Maths  Physics  Chemistry  Accounting  B.S
0  Prabha     67       48         57          87   58
1   James     89       57         78          88  100
2   Susan     92       91         31          91   99


In [28]:
data_2

array([['Prabha', '67', '48', '57', '87', '58'],
       ['James', '89', '57', '78', '88', '100'],
       ['Susan', '92', '91', '31', '91', '99']], dtype='<U11')

In [55]:
#in majority of the cases, string data is taken as Unicode characters.


In [110]:
#np.random.random()
random_temps = np.random.random((5,7))*10000
random_temps

array([[8203.93875213, 1475.01966822,  658.31401113, 1503.90849702,
        7690.22875364, 3468.4024203 , 2974.02372498],
       [2080.89077083, 3661.24686273, 3934.22775072, 2451.93283906,
        7655.11970387, 7876.38869515, 1001.91286973],
       [ 255.82333524, 4506.98322082, 6744.64961418, 7527.30419758,
        6614.40507249, 9807.48336333, 3416.3735452 ],
       [  96.3240058 , 8213.3350919 , 2071.3429634 ,  729.27092938,
        5620.69644753, 1231.10040324, 8941.20402308],
       [7376.87984755, 5313.52616424, 1631.49917144, 7039.17554384,
        8958.6800067 , 6898.48285717, 8588.99029744]])

In [102]:
#np.random.random()
random_temps = np.random.random((5,7))*10+25
random_temps

array([[25.68146589, 32.42635779, 32.29457835, 31.93961565, 29.13716508,
        33.93661678, 30.71047196],
       [31.39985148, 25.97747509, 30.66169417, 29.73455483, 28.08801101,
        31.89839075, 31.78047327],
       [34.8967763 , 26.43850714, 30.58396064, 33.85791199, 25.68457295,
        25.50953022, 32.75695786],
       [27.93021018, 28.26954653, 25.36417257, 25.99944783, 29.00760783,
        33.68840513, 33.19264641],
       [32.35437086, 28.5531741 , 26.88704358, 31.08276535, 30.82506157,
        30.71792615, 25.37750487]])

### 2. Reshaping Methods: - 

In [121]:
#Reshape: - 
wert = np.arange(1,7).reshape((2,3))
wert

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
wert_1 = np.arange(1,7)
wert_1

array([1, 2, 3, 4, 5, 6])

In [125]:
#Ravel: - flattens an array into 1D array
yui = np.array([[1,2],[3,4]])
flat = yui.ravel()
flat

array([1, 2, 3, 4])

In [127]:
yui

array([[1, 2],
       [3, 4]])

#### 3. Statistical Methods 

In [6]:
import numpy as np
rty = np.array([1,2,3,4])

In [14]:
# Sum of all the elements: - 
print(rty.sum())
print(rty.mean())
print(rty.max())
print(rty.min())

10
2.5
4
1


In [56]:
rty1 = np.array([5,6,7,8])
rty2 = np.array([5,8,9,4])
print(np.add(rty1,rty2))
print(np.subtract(rty1,rty2))
print(np.multiply(rty1,rty2))
print(np.divide(rty1,rty2))

[10 14 16 12]
[ 0 -2 -2  4]
[25 48 63 32]
[1.         0.75       0.77777778 2.        ]


In [24]:
# Logical Operations: - 
# all() : - Returns True if all the elements satisfy a condition
# any() : - Returns True if any of the elements satisfy a condition

In [40]:
yop = np.array([0,1,2])
print(yop.all())
print(yop.any())

False
True


In [54]:
# Array Sorting & Searching: - 
ghj = np.array([5,8,7,9])
sorted = np.sort(ghj)
print(sorted)
# argmax()/argmin() : - Returns the index # of the max/min element
print(ghj.argmax())
print(ghj.argmin())

[5 7 8 9]
3
0


In [68]:
# Array Split: - 
hjl = np.array([8,7,9,6,12,15])
split_tyu = np.split(hjl,3)
print(split_tyu)

[array([8, 7]), array([9, 6]), array([12, 15])]


#### Reading the Text Data using Numpy: - 

In [15]:
pwd

'C:\\Users\\ADMIN1\\Jupyters_Ria_Arnav\\Ria_JPNBs'

In [17]:
data = np.loadtxt('numpy_load.txt')

In [19]:
data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [27]:
file_path = 'data_mixed.txt'

In [29]:
file_path

'data_mixed.txt'

In [31]:
pwd

'C:\\Users\\ADMIN1\\Jupyters_Ria_Arnav\\Ria_JPNBs'

In [82]:
data_rf = np.genfromtxt(
                        file_path, 
                        delimiter = '|', 
                        dtype = None,
                        encoding = 'utf-8',
                        filling_values = np.nan
                       )

In [84]:
data_rf

array([(1., ' 2.0', ' 3.0'), (4., 'ria', ' 6.0'), (7., ' 8.0', ' nine')],
      dtype=[('f0', '<f8'), ('f1', '<U4'), ('f2', '<U5')])

In [90]:
import pandas as pd
data_rft = pd.DataFrame(data_rf)

In [94]:
cols = ['ID','ID_1','ID_2']

In [104]:
#renaming the columns: - 
data_rft.columns = cols

In [1]:
data_rft.to_excel('rft.xlsx',index=False)

NameError: name 'data_rft' is not defined

### Array Math: - 

In [6]:
# Array math using numpy is used to do certain numeric calculations in between the arrays. 
import numpy as np

In [8]:
sales_data = np.array([
    [500, 700, 800,600],
    [450,650,750,550],
    [800,900,1000,750],
    [300,400,500,450],
    [600,700,800,650]
])

In [10]:
print("Sales data (in USD):")
print(sales_data)

Sales data (in USD):
[[ 500  700  800  600]
 [ 450  650  750  550]
 [ 800  900 1000  750]
 [ 300  400  500  450]
 [ 600  700  800  650]]


In [20]:
## Operations: - 
#1. total sales per product: - 
total_sales_per_product = sales_data.sum(axis=0)
print(total_sales_per_product)

[2650 3350 3850 3000]


In [22]:
#2. average sales per month: - 
avg_sales_per_month = sales_data.mean(axis=0)
print(avg_sales_per_month)

[530. 670. 770. 600.]


In [26]:
# Increase the sales by 10%: - 
increased_sales = sales_data*1.1
print(increased_sales)

[[ 550.  770.  880.  660.]
 [ 495.  715.  825.  605.]
 [ 880.  990. 1100.  825.]
 [ 330.  440.  550.  495.]
 [ 660.  770.  880.  715.]]


In [56]:
# 5. Percentage Contribution of each product
total_sales = sales_data.sum()
percentage_contribution = (total_sales_per_product/total_sales)*100
percentage_contribution

array([20.62256809, 26.07003891, 29.96108949, 23.3463035 ])

In [58]:
#exam scores for 6 students: - 
exam_scores = np.array([
    [85,90,78,92], # st. 1
    [88,76,95,89], # st. 2
    [92,88,82,85], # st. 3
    [70,65,75,80], # st. 4
    [95,92,90,96], # st. 5
    [60,72,68,75] #  st. 6
])

###### 1. What is the average score of each student 
###### 2. What is the highest score in each subject
###### 3. Which students scored below 70 in any subject?
###### 4. Which subjects have an average score above 85?
###### 5. Which student has the highest total score?
###### 6. Increase all scores by 5%