In [1]:
import numpy as np
#Linear Algebra, Determinants & Matrices: - 
#We use this library to form data arrays using python which is a homogentic arrangement of elements across the structure.
#we require this to make data arrays and so that the data can be analyzed perfectly.

In [2]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [3]:
#Dimension of an array: - 
a.ndim

2

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.itemsize

4

In [6]:
a.shape

(3, 3)

In [7]:
#Scalar (0 D Array): - np.array([])
scalar = np.array(1)
print("Scalar",scalar)
print("ndim:",scalar.ndim)

#1D Array: - 
arr_1d = np.array([1,2,3,4])
print("\n1D Array:",arr_1d)
print("ndim:",arr_1d.ndim)

#2D Array: - 
arr_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D Array:",arr_2d)
print("ndim:",arr_2d.ndim)

#3D Array: - np.array([[[]]])
#list brackets from l-r: -
#1. array bracket
#2. block bracket
#3. elements for the rows and columns bracket
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)

Scalar 1
ndim: 0

1D Array: [1 2 3 4]
ndim: 1

2D Array: [[1 2 3]
 [4 5 6]]
ndim: 2

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [8]:
# 2 code blocks, 2 rows & 2 columns
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)


3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [9]:
# 2 groups, 2 code blocks, 3 rows & 4 columns
arr_4d = np.array([
    [ # First Group
        [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #First Block
        [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #Second Block
    ],
    [# Second Group
        [[25,26,27,28],[29,30,31,32],[33,34,35,36]],
        [[37,38,39,40],[41,42,43,44],[45,46,47,48]]
    ]
])
print("\n4D Array:",arr_4d)
print("ndim:",arr_4d.ndim)
#5D array for me?


4D Array: [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
ndim: 4


### Data Manipulations using Arrays: -

In [11]:
import numpy as np

In [12]:
#Create a 3D array - 
array_3d = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #first Block
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #second Block
])

print("3d_Array:")
print(array_3d)

#Shape of the array: - (Output Syntax: - Block, Row, Column)
print("\n shape of the array is:",array_3d.shape)

#Access elements: - (Output Syntax: - Indices # of [Block, Row, Column])
print("\nElement at block 1, row 2, column 3:",array_3d[0,1,2])
print("\nElement at block 2, row 3, column 2:",array_3d[1,2,1])

#Access all the elements: - 
print("\n Second Block: ")
print(array_3d[1])

#Access the specific set of elements: - 
print("\n first column of each block")
print(array_3d[:,:,0])

print("\n first row of each block")
print(array_3d[:,0,:])

print("\n specific set of elements") #Indices of [Block, Row, Column]
result = (array_3d[0,0:2,0:2])
result_1 = (array_3d[1,1:3,2:4])

print("\n specific set of sliced elements")
result_2 = (array_3d[:,1,1:3]) 

print("\n Extracted Elements:")
print(result.flatten())

print("\n Extracted Elements:")
print(result_1.flatten())

print("\n Extracted Elements:")
print(result_2.flatten())

3d_Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

 shape of the array is: (2, 3, 4)

Element at block 1, row 2, column 3: 7

Element at block 2, row 3, column 2: 22

 Second Block: 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

 first column of each block
[[ 1  5  9]
 [13 17 21]]

 first row of each block
[[ 1  2  3  4]
 [13 14 15 16]]

 specific set of elements

 specific set of sliced elements

 Extracted Elements:
[1 2 5 6]

 Extracted Elements:
[19 20 23 24]

 Extracted Elements:
[ 6  7 18 19]


## Array Methods: - 

### 1. Array creation Methods

In [15]:
# np.array() - Converts a list or a tuple into an array.: - Vectors | Vector Algebra!
arr_345 = np.array([1,2,3,4])
arr_345

array([1, 2, 3, 4])

In [16]:
#Practical Application: - 
'''We are considering a weather monitoring system where we collect 
temperature data for varios cities over several days'''

temps_manual = np.array([[30,32,33,35,31,29,30], # Temperature of City_1
                         [28,27,29,31,30,26,27]]) #Temperature of City_2

In [17]:
#np.zeroes() - Creates an array filled with zeroes.
arr_678 = np.zeros((2,3))
arr_678

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#Practical Application: -
temps_empty = np.zeros((5,7))
print(temps_empty)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
#np.ones() - Creates an array filled with ones.
arr_897 = np.ones((2,3))
arr_897

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#Practical Application: -
temps_ones = np.ones((5,7))

In [6]:
#np.arange() - creates an array with a range of numbers.
import numpy as np
art_978 = np.arange(1,11,3)
art_978
art_972 = np.arange(1,32,4)
art_972

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [22]:
art_978

array([ 1,  4,  7, 10])

In [23]:
#Practical Application: -

timestamps = np.arange(0,24,1)
timestamps

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
#np.linspace(): - Creates an array with evenly spaced numbers
art_765 = np.linspace(0,2,5)
art_765 

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
#Practical Application: -

'''Record evenly spaced temperatures between highest and lowest values.'''

lin_temp = np.linspace(26,35,5)
lin_temp

array([26.  , 28.25, 30.5 , 32.75, 35.  ])

In [26]:
art_765

array([0. , 0.5, 1. , 1.5, 2. ])

#### To make any data a dataframe: - 

In [28]:
#Pandas Solution: - 
data = {
    "Name": ["Prabha","James","Susan"],
    "Maths": [67,89,92],
    "Physics": [48,57,91]
}

In [29]:
data

{'Name': ['Prabha', 'James', 'Susan'],
 'Maths': [67, 89, 92],
 'Physics': [48, 57, 91]}

In [30]:
import pandas as pd
df_1 = pd.DataFrame(data)

In [31]:
df_1

Name  Maths  Physics
0  Prabha     67       48
1   James     89       57
2   Susan     92       91

In [32]:
#numpy solution: - 
data_2 = np.array(
    [
    ("Prabha", 67,48,57,87,58),
    ("James", 89,57,78,88,100),
    ("Susan", 92,91,31,91,99)
],
dtype = [("Name","U10"),("Maths","i4"),("Physics","i4"),("Chemistry","i4"),("Accounting","i4"), ("B.S", "i4")]                 
)
dft = pd.DataFrame(data_2)
print("\n structured data shall be: ")
print(dft)


 structured data shall be: 
     Name  Maths  Physics  Chemistry  Accounting  B.S
0  Prabha     67       48         57          87   58
1   James     89       57         78          88  100
2   Susan     92       91         31          91   99


In [33]:
data_2

array([('Prabha', 67, 48, 57, 87,  58), ('James', 89, 57, 78, 88, 100),
       ('Susan', 92, 91, 31, 91,  99)],
      dtype=[('Name', '<U10'), ('Maths', '<i4'), ('Physics', '<i4'), ('Chemistry', '<i4'), ('Accounting', '<i4'), ('B.S', '<i4')])

In [34]:
#in majority of the cases, string data is taken as Unicode characters.


In [12]:
#np.random.random()
random_temps = np.random.random((5,7))*100
random_temps

array([[17.6244564 , 81.3600992 , 47.4559862 , 16.65427475, 81.85600955,
        36.81364981, 39.51051874],
       [69.16943626, 19.51869197, 98.73994813, 35.23466324, 41.99023802,
        86.51549621, 27.76093518],
       [85.09300336, 22.71792191, 16.38659226, 93.35396269, 75.61199902,
        32.74560998, 23.22614739],
       [96.68651849, 83.19689091, 58.37822996, 82.16906286,  3.07551178,
        58.26480704, 37.32809816],
       [39.33766863, 59.55987963, 93.56820828, 15.18091658, 92.75808715,
        15.83977125, 60.58911084]])

In [36]:
#np.random.random()
random_temps = np.random.random((5,7))*10+25
random_temps

array([[32.5036295 , 29.04768934, 33.1572164 , 33.37488521, 32.49018075,
        32.77096314, 33.06599812],
       [28.32702524, 31.97459121, 26.8916047 , 25.16850424, 33.96435302,
        25.33831287, 26.85903485],
       [32.2052402 , 29.99842414, 31.60940881, 29.58450799, 25.80892849,
        25.33407375, 27.49255849],
       [27.20508755, 25.80783716, 34.13215825, 29.31629006, 27.15575334,
        27.20675491, 30.5767582 ],
       [27.3554349 , 34.25516676, 34.20239032, 30.92894582, 29.56298663,
        30.91969285, 31.28106775]])

### 2. Reshaping Methods: - 

In [38]:
#Reshape: - 
wert = np.arange(1,7).reshape((2,3))
wert

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
wert_1 = np.arange(1,7)
wert_1

array([1, 2, 3, 4, 5, 6])

In [40]:
#Ravel: - flattens an array into 1D array
yui = np.array([[1,2],[3,4]])
flat = yui.ravel()
flat

array([1, 2, 3, 4])

In [41]:
yui

array([[1, 2],
       [3, 4]])

#### 3. Statistical Methods 

In [2]:
import numpy as np
rty = np.array([1,2,3,4])

In [3]:
# Sum of all the elements: - 
print(rty.sum())
print(rty.mean())
print(rty.max())
print(rty.min())

10
2.5
4
1


In [5]:
rty1 = np.array([5,6,7,8])
rty2 = np.array([5,8,9,4])
print(np.add(rty1,rty2))
print(np.subtract(rty2,rty1))
print(np.multiply(rty1,rty2))
print(np.divide(rty1,rty2))

[10 14 16 12]
[ 0  2  2 -4]
[25 48 63 32]
[1.         0.75       0.77777778 2.        ]


In [46]:
# Logical Operations: - 
# all() : - Returns True if all the elements satisfy a condition
# any() : - Returns True if any of the elements satisfy a condition

In [47]:
yop = np.array([0,1,2])
print(yop.all())
print(yop.any())

False
True


In [48]:
# Array Sorting & Searching: - 
ghj = np.array([5,8,7,9])
sorted = np.sort(ghj)
print(sorted)
# argmax()/argmin() : - Returns the index # of the max/min element
print(ghj.argmax())
print(ghj.argmin())

[5 7 8 9]
3
0


In [49]:
# Array Split: - 
hjl = np.array([8,7,9,6,12,15])
split_tyu = np.split(hjl,3)
print(split_tyu)

[array([8, 7]), array([9, 6]), array([12, 15])]


#### Reading the Text Data using Numpy: - 

In [6]:
pwd

'/Users/arnav/Documents/GitHub/Ria_JPNBs'

In [7]:
data = np.loadtxt('numpy_load.txt')

In [8]:
data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [54]:
file_path = 'data_mixed.txt'

In [55]:
file_path

'data_mixed.txt'

In [56]:
pwd

'C:\\Users\\ADMIN1\\Jupyters_Ria_Arnav\\Ria_JPNBs'

In [57]:
data_rf = np.genfromtxt(
                        file_path, 
                        delimiter = '|', 
                        dtype = None,
                        encoding = 'utf-8',
                        filling_values = np.nan
                       )

In [58]:
data_rf

array([(1., ' 2.0', ' 3.0'), (4., 'ria', ' 6.0'), (7., ' 8.0', ' nine')],
      dtype=[('f0', '<f8'), ('f1', '<U4'), ('f2', '<U5')])

In [59]:
import pandas as pd
data_rft = pd.DataFrame(data_rf)

In [60]:
cols = ['ID','ID_1','ID_2']

In [61]:
#renaming the columns: - 
data_rft.columns = cols

In [62]:
data_rft.to_excel('rft.xlsx',index=False)

### Array Math: - 

In [1]:
# Array math using numpy is used to do certain numeric calculations in between the arrays. 
import numpy as np

In [2]:
sales_data = np.array([
    [500, 700, 800,600],
    [450,650,750,550],
    [800,900,1000,750],
    [300,400,500,450],
    [600,700,800,650]
])

In [3]:
print("Sales data (in USD):")
print(sales_data)

Sales data (in USD):
[[ 500  700  800  600]
 [ 450  650  750  550]
 [ 800  900 1000  750]
 [ 300  400  500  450]
 [ 600  700  800  650]]


In [5]:
## Operations: - 
#1. total sales per product: - 
total_sales_per_product = sales_data.sum(axis=0)
print(total_sales_per_product)

[2650 3350 3850 3000]


In [68]:
#2. average sales per month: - 
avg_sales_per_month = sales_data.mean(axis=0)
print(avg_sales_per_month)

[530. 670. 770. 600.]


In [69]:
# Increase the sales by 10%: - 
increased_sales = sales_data*1.1
print(increased_sales)

[[ 550.  770.  880.  660.]
 [ 495.  715.  825.  605.]
 [ 880.  990. 1100.  825.]
 [ 330.  440.  550.  495.]
 [ 660.  770.  880.  715.]]


In [70]:
# 5. Percentage Contribution of each product
total_sales = sales_data.sum()
percentage_contribution = (total_sales_per_product/total_sales)*100
percentage_contribution

array([20.62256809, 26.07003891, 29.96108949, 23.3463035 ])

In [71]:
#exam scores for 6 students: - 
exam_scores = np.array([
    [85,90,78,92], # st. 1
    [88,76,95,89], # st. 2
    [92,88,82,85], # st. 3
    [70,65,75,80], # st. 4
    [95,92,90,96], # st. 5
    [60,72,68,75] #  st. 6
])

###### 1. What is the average score of each student 
###### 2. What is the highest score in each subject
###### 3. Which students scored below 70 in any subject?
###### 4. Which subjects have an average score above 85?
###### 5. Which student has the highest total score?
###### 6. Increase all scores by 5%

### Array Comparison: - 

#### Array Intersection: - helps to find the elements which are common in both the arrays

In [75]:
import numpy as np
trw = [1,2,3,4,5,6]
qas = [4,5,6,7,8,9]
common_elements = np.intersect1d(trw,qas)
common_elements

array([4, 5, 6])

#### Array Differences: - identifies the elements which are in one array but not in another

In [77]:
difference = np.setdiff1d(trw,qas)
difference

array([1, 2, 3])

#### **Element wise equality: - this function checks whether if each element in one array exists in the other

In [79]:
is_in_array = np.isin(qas,trw)
is_in_array

array([ True,  True,  True, False, False, False])

#### Unique elements : - this helps to check the unique set of elements.

In [81]:
unique_elements = np.union1d(trw,qas)
unique_elements

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array Filtering: - 

In [83]:
asdf = np.array([6,7,8,9,10])

filtered_array = asdf[(asdf > 7) & (asdf < 9)]
filtered_array

array([8])

#### Combining Arrays: - 

In [3]:
#1. Vertical Stacking: - 
import numpy as np
qgh = np.array([5,6,7,8,9,2])
tre = np.array([10,11,12,13,14,19])
vstack = np.vstack((qgh,tre))
print("the shape is:",vstack.shape)
vstack

the shape is: (2, 6)


array([[ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14, 19]])

In [4]:
#2. Horizontal Stacking: - 
hstack = np.hstack((qgh,tre))
hstack.shape
hstack

array([ 5,  6,  7,  8,  9,  2, 10, 11, 12, 13, 14, 19])

In [87]:
vstack

array([[ 5,  6,  7,  8,  9,  2],
       [10, 11, 12, 13, 14, 19]])

In [88]:
hstack

array([ 5,  6,  7,  8,  9,  2, 10, 11, 12, 13, 14, 19])

In [5]:
reshaped34 = qgh.reshape(2,3)
reshaped35 = tre.reshape(2,3)

In [90]:
#3. Array Concatenation: - 
concat_result = np.concatenate((reshaped34,reshaped35),axis=1)
concat_result

array([[ 5,  6,  7, 10, 11, 12],
       [ 8,  9,  2, 13, 14, 19]])

In [8]:
reshaped34.ndim

2