In [3]:
import numpy as np
#Linear Algebra, Determinants & Matrices: - 
#We use this library to form data arrays using python which is a homogentic arrangement of elements across the structure.
#we require this to make data arrays and so that the data can be analyzed perfectly.

In [5]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [7]:
#Dimension of an array: - 
a.ndim

2

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.itemsize

4

In [13]:
a.shape

(3, 3)

In [15]:
#Scalar (0 D Array): - 
scalar = np.array(56)
print("Scalar",scalar)
print("ndim:",scalar.ndim)

#1D Array: - 
arr_1d = np.array([1,2,3,4])
print("\n1D Array:",arr_1d)
print("ndim:",arr_1d.ndim)

#2D Array: - 
arr_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D Array:",arr_2d)
print("ndim:",arr_2d.ndim)

#3D Array: - 
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)

Scalar 56
ndim: 0

1D Array: [1 2 3 4]
ndim: 1

2D Array: [[1 2 3]
 [4 5 6]]
ndim: 2

3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [17]:
# 2 code blocks, 2 rows & 2 columns
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:",arr_3d)
print("ndim:",arr_3d.ndim)


3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3


In [19]:
# 2 groups, 2 code blocks, 3 rows & 4 columns
arr_4d = np.array([
    [ # First Group
        [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #First Block
        [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #Second Block
    ],
    [# Second Group
        [[25,26,27,28],[29,30,31,32],[33,34,35,36]],
        [[37,38,39,40],[41,42,43,44],[45,46,47,48]]
    ]
])
print("\n4D Array:",arr_4d)
print("ndim:",arr_4d.ndim)


4D Array: [[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
ndim: 4


### Data Manipulations using Arrays: -

In [22]:
import numpy as np

In [28]:
#Create a 3D array - 
array_3d = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]], #first Block
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]] #second Block
])

print("3d_Array:")
print(array_3d)

#Shape of the array: - (Output Syntax: - Block, Row, Column)
print("\n shape of the array is:",array_3d.shape)

#Access elements: - (Output Syntax: - Indices # of [Block, Row, Column])
print("\nElement at block 1, row 2, column 3:",array_3d[0,1,2])
print("\nElement at block 2, row 3, column 2:",array_3d[1,2,1])

#Access all the elements: - 
print("\n Second Block: ")
print(array_3d[1])

#Access the specific set of elements: - 
print("\n first column of each block")
print(array_3d[:,:,0])

print("\n first row of each block")
print(array_3d[:,0,:])

print("\n specific set of elements") #Indices of [Block, Row, Column]
result = (array_3d[0,0:2,0:2])
result_1 = (array_3d[1,1:3,2:4])

print("\n specific set of sliced elements")
result_2 = (array_3d[:,1,1:3]) 

print("\n Extracted Elements:")
print(result.flatten())

print("\n Extracted Elements:")
print(result_1.flatten())

print("\n Extracted Elements:")
print(result_2.flatten())

3d_Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

 shape of the array is: (2, 3, 4)

Element at block 1, row 2, column 3: 7

Element at block 2, row 3, column 2: 22

 Second Block: 
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

 first column of each block
[[ 1  5  9]
 [13 17 21]]

 first row of each block
[[ 1  2  3  4]
 [13 14 15 16]]

 specific set of elements

 specific set of sliced elements

 Extracted Elements:
[1 2 5 6]

 Extracted Elements:
[19 20 23 24]

 Extracted Elements:
[ 6  7 18 19]


## Array Methods: - 

### Array creation Methods

In [36]:
# np.array() - Converts a list or a tuple into an array.
arr_345 = np.array([1,2,3,4])
arr_345

array([1, 2, 3, 4])

In [42]:
#np.zeroes() - Creates an array filled with zeroes.
arr_678 = np.zeros((2,3))
arr_678

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
#np.ones() - Creates an array filled with ones.
arr_897 = np.ones((2,3))
arr_897

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
#np.arange() - creates an array with a range of numbers.
art_978 = np.arange(1,11,3)

In [56]:
art_978

array([ 1,  4,  7, 10])